### ISSUE TITLE
/var/www/owncloud/data/updater_backup/100.0.0.0.tar.bz2 extraction error

### ISSUE THREAD

**Issue by carlaschroder** [owncloud/updater#188]
Help please:

### Steps to reproduce
1. Enable Updater app
2. Enable Daily channel on admin page (for fastest testing)
3. Click Update button

### Expected behaviour
Updater should make backup, download and unpack current archive, and then install it

### Actual behaviour
Updater makes backup, then stops with "/var/www/owncloud/data/updater_backup/100.0.0.0.tar.bz2 extraction error"

### Server configuration
Linux Mint 17.1
**Web server:**
Apache/2.4.7
**Database:**
mysql  Ver 15.1 Distrib 5.5.46-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
**PHP version:**
PHP 5.5.9
**ownCloud version:** (see ownCloud admin page)
ownCloud 8.2.1 RC3 (daily) 
**Updated from an older ownCloud or fresh install:**
Fresh install
**List of activated apps:**
Enabled:
  - activity: 2.1.3
  - files: 1.2.0
  - files_locking: 
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - notifications: 0.1.0
  - provisioning_api: 0.3.0
  - templateeditor: 0.1
  - updater: 0.6

**The content of config/config.php:**
  'instanceid' => 'foo',
  'passwordsalt' => 'BJFGRedIZhJtL638SobbwTrE/4w3F+',
  'secret' => 'foo',
  'trusted_domains' => 
  array (
    0 => 'localhost',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'http://localhost/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.2.1.2',
  'dbname' => 'ocdb2',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'foo',
  'dbpassword' => 'foo',
  'logtimezone' => 'UTC',
  'installed' => true,

![updater-fails](https://cloud.githubusercontent.com/assets/8388387/11219791/5c7689aa-8d11-11e5-8c16-f41ab1f1294f.png)

**Comment by VicDeo** [comment]
@carlaschroder  what `php -m | grep bz2` say?

**Comment by carlaschroder** [comment]
Hi @VicDeo :

php -m | grep bz2
bz2

**Comment by VicDeo** [comment]
@carlaschroder hi!
is /var/www/owncloud/data/updater_backup/100.0.0.0.tar.bz2  a valid tar package?

**Comment by RealRancor** [comment]
Looks like related to https://github.com/owncloud/updater/issues/128

**Comment by carlaschroder** [comment]
@VicDeo It looks like it is:

sudo tar -xjvf 100.0.0.0.tar.bz2
ls
100.0.0.0.tar.bz2  owncloud
ls -c1
index.php
resources
status.php
lib
ocs-provider
settings
version.php
core
index.html
apps
db_structure.xml
public.php
remote.php
3rdparty
console.php
cron.php
ocs
robots.txt
themes
AUTHORS
config
COPYING-AGPL
l10n
occ

du -sh owncloud
109M    owncloud/

**Comment by VicDeo** [comment]
@carlaschroder is  there `_oc-upgrade` directory under `/var/www/owncloud`?

**Comment by VicDeo** [comment]
@RealRancor not exactly. #128 was fixed in core.

**Comment by carlaschroder** [comment]
@VicDeo , there is not an _oc_upgrade directory. Yay, does this mean we're getting close to an answer? Thanks for helping.

owncloud$ ls -C1
3rdparty
apps
AUTHORS
config
console.php
COPYING-AGPL
core
cron.php
data
db_structure.xml
index.html
index.php
indie.json
l10n
lib
occ
ocs
ocs-provider
owncloud
public.php
remote.php
resources
robots.txt
settings
status.php
themes
version.php

**Comment by VicDeo** [comment]
@carlaschroder looks like mimetype detection for tar.bz2 is broken  in core/master

**Comment by VicDeo** [comment]
@carlaschroder you need to add
`	"bz2": ["application/x-bzip2"],`
to `resources/config/mimetypemapping.dist.json`

**Comment by carlaschroder** [comment]
Hrm... still getting the same error. I also tried adding  "tar.bz2: ["application/x-gtar"], which did not help either. I'll try a different installation, as this one is pretty mangled.

**Comment by VicDeo** [comment]
@carlaschroder it should be `"application/x-bzip2"` exactly. Reason is https://github.com/owncloud/core/blob/master/lib/private/archive.php#L47

**Comment by VicDeo** [comment]
it's not an updater bug that core consider `bz2` archives to be uncommon ;)

**Comment by carlaschroder** [comment]
Thanks @VicDeo, but it still gives the same error message on a fresh installation, 8.2.1 on the daily channel. Adding "bz2": ["application/x-bzip2"], to resources/config/mimetypemapping.dist.json had no effect. I'll try it on CentOS to see if that makes any difference.

**Comment by VicDeo** [comment]
@carlaschroder 8.2.1? You need https://github.com/owncloud/core/commit/a543d20958592f0d354d1629c7408121eaabd8a7
in this case

**Comment by carlaschroder** [comment]
> aaand it's not an updater bug that core consider bz2 archives to be uncommon ;)

OK, I do not blame Updater app :)

**Comment by VicDeo** [comment]
@carlaschroder so, have you tried the [another core patch needed for 8.1 ](https://github.com/owncloud/core/commit/a543d20958592f0d354d1629c7408121eaabd8a7) I posted in above message?

**Comment by carlaschroder** [comment]
Not yet, I'll try to get to it today.

**Comment by carlaschroder** [comment]
https://github.com/owncloud/core/commit/a543d20958592f0d354d1629c7408121eaabd8a7 works perfectly in 8.2, hurrah! However, 8.1 throws an error "upgrades to major versions not supported." 8.1 tries to upgrade to 100.0.0.0 just like 8.2.

**Comment by VicDeo** [comment]
@carlaschroder ah. https://github.com/owncloud/updater/pull/179 was backported to stable8.2 only.
8.1.x is not capable to upgrade to version 100 :(

**Comment by VicDeo** [comment]
@carlaschroder this time you need to patch updater ( 8.1.x only, 8.2 already contains this change)
https://github.com/owncloud/updater/pull/196/files

### Summary by message and version

1. bz2 support `*.bz2 extraction error`  
I. **all versions** add bz2 to known mimetypes: 
` "bz2": ["application/x-bzip2"],`  to `mimetypemapping.dist.json`
II. **8.2.x and below** https://github.com/owncloud/core/commit/a543d20958592f0d354d1629c7408121eaabd8a7


2. `upgrades to major versions not supported.`
**8.1.x.**  https://github.com/owncloud/updater/pull/196 (To be released with 8.1.5)

**Comment by carlaschroder** [comment]
Thanks @VicDeo, I'll try this when I am finished overhauling the  upgrading manual pages.

**Comment by carlaschroder** [comment]
@VicDeo Allrightythen. The bz2 patches work. I'm still not clear on major version upgrades-- is the Updater supposed to do major upgrades?

**Comment by VicDeo** [comment]
@carlaschroder 
>is the Updater supposed to do major upgrades?

I'd say yes. E.g. 6 to 7 and 7 to 8. 
But as soon as feed recommends 8.2.1 to be an upgrade candidate for 6.0  `https://updates.owncloud.com/server/?version=6x0x0x0x1423763974.698x1446495849xproductionxxNo` it's impossible to upgrade 6.x via updater.

**Comment by VicDeo** [comment]
I've reported this long ago btw https://github.com/owncloud/appstore-issues/issues/4

**Comment by carlaschroder** [comment]
Skipping major releases is not supported, so the Updater app is fine :) Thanks for all your help, closing this now because we're done!

**Comment by VicDeo** [comment]
@carlaschroder yep, it's not supported. But it is our own upgrade server who tells OC 6.x 'you heed to get 8.2.1 for upgrade' as I described in appstore issue mentioned above .
